config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  # get 'tweets/search'
  resources :tweets
  resources :trips
  resources :users
  resources :relationships
  resources :bookmarks
  # get 'spot', to: 'tweets#new_spot'
  #   post 'spot', to: 'tweets#create_spot'
  
    resource :users do
    resource :relationships, only: [:create, :destroy, :show,]
  end


 

  resources :tweets do
    resource :bookmarks
  end

  resources :trips do
    resource :bookmark_trips
  end
  
  resources :tweets do
    resources :comments, only: :create
  end

  resources :trips do
    resources :trip_comments, only: :create
  end
  
  resources :tweets do
    resources :users
  end

  resources :trips do
    resources :users
  end

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates :user_id, uniqueness: { scope: :tweet_id } # 追加
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    
     @tweet = Tweet.find(params[:tweet_id])
    bookmark = @tweet.bookmarks.new(user_id: current_user.id)
    if bookmark.save
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  

  
  

  
  end

  def destroy
   @tweet = Tweet.find(params[:tweet_id])
    bookmark = @tweet.bookmarks.find_by(user_id: current_user.id)
    if bookmark.present?
        bookmark.destroy
        redirect_to request.referer
    else
        redirect_to request.referer
    end

  

  end

  def show
    @bookmark = Bookmark.all.order("created_at DESC")
  end

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/show.html.erb
<table>
  <caption>宿泊施設お気に入り一覧</caption>
  <div>
  <tbody>
  
    <% @bookmark.each do |bookmark| %>
      <tr>
        <td><%= bookmark.tweet.user.nickname %></td>
        <td>
          <%= link_to tweet_path(bookmark.tweet) do %>
            <%= bookmark.tweet.title %>
          <% end %>
        </td>
        <td><%= bookmark.tweet.images %></td>
      <td><%=link_to 'もどる', user_path(current_user.id), class:"back-btn" %></td>
      
      </tr>


       
    <% end %>
    
  </tbody>
</table>
 