config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  # get 'tweets/search'
  resources :tweets
  resources :trips
  resources :users
  resources :relationships
  resources :bookmarks
  # get 'spot', to: 'tweets#new_spot'
  #   post 'spot', to: 'tweets#create_spot'
  
    resource :users do
    resource :relationships, only: [:create, :destroy, :show,]
  end


 

  resources :tweets do
    resource :bookmarks
  end

  resources :trips do
    resource :bookmark_trips
  end
  
  resources :tweets do
    resources :comments, only: :create
  end

  resources :trips do
    resources :trip_comments, only: :create
  end
  
  resources :tweets do
    resources :users
  end

  resources :trips do
    resources :users
  end

end

app/models/trip.rb
class Trip < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many_attached :images
  has_many :bookmark_trips, dependent: :destroy
  has_many :trip_comments  # commentsテーブルとのアソシエーション

  
  def bookmark_by?(user)
    bookmark_trips.where(user_id: user.id).exists?
  end


  belongs_to_active_hash :area
  belongs_to_active_hash :crowd
  belongs_to_active_hash :week
  

  validates :area_id, numericality: { other_than: 1 }
  validates :images,:local, :title, :price,:spot_text,presence: true
  # validates :video, :presence => true

  #動画投稿機能
  # mount_uploader :video, VideoUploader

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    # @trips = Trip.all.order(created_at: :desc)
    @trips = Trip.all.includes(:user)
  end  


  def new
    @trip = Trip.new
  
  end

  def create
    @trip = Trip.new(trip_params)
    
    if @trip.save
      redirect_to  root_path
    else 
      render :new
    end
  end
  
  
  def show
    @trip = Trip.find(params[:id])
    @trips = Trip.all.includes(:user)
    @comment = TripComment.new
    @comments = @trip.trip_comments.includes(:user)
  end
      

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
    
    respond_to do |format|
      if @article.update(article_params) && @article.video.recreate_versions!
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    if @trip.destroy
      redirect_to root_path
    end
  end

  def bookmarks
    @trips = current_user.bookmark_boards.includes(:user).recent
end

  private

  def trip_params
    params.require(:trip).permit(:video,:price,:discount,:area_id,:week_id,:crowd_id,:title,:spot_text,:corona_measure,:traffic,:fare,:local,  images: []).merge(user_id: current_user.id)
  end
  
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>

  </header>

<%# 観光の情報 %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">観光スポット</h2>
    <%= form_with  model: @trip,local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>



   

    
    <%# 旅行タイトル %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <%# /旅行タイトル %>

      
 <%# 観光の詳細%>
     
      <%# 観光スポットの画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'trip[images][]', id:"travel-image" %>
        <div id="image-list"></div>
      </div>
    </div>

    <% @trip.images.each do |image| %>
  <%= image_tag image, class: 'images' %>
<% end %>
    <%# /観光スポットの画像 %>

<%# 観光スポットの動画 %>

    <div class="field">
    <%= f.label :video %>
    <%= f.file_field :video, :accept => 'video/*' %>
</div>
<%# /観光スポットの動画 %>
   
    <%# 観光曜日%>  
         <div class="weight-bold-text">
          観光した曜日
         
        </div>
        <%= f.collection_select(:week_id, Week.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    <%# /観光曜日%>  
      
       <%# 観光スポットの場所%>  
 <div class="hotel-detail">
      <div class="weight-bold-text">旅行の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :local, class:"hotel-area", id:"item-name", placeholder:"地域（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>
   <%# /観光スポットの場所%>  
     
     <%# 観光スポットの料金%>  
     <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>料金</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>料金(割引後)</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）5000" %>
        </div>
      </div>
    </div>
    <div class="weight-bold-text">
          元値
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_area :discount, class:"hotel-area", id:"item-name", placeholder:"例）5000", maxlength:"40" %>
        <span class="sell-yen"></span>
     <%# 観光スポットの料金%>  


      <%# コロナ対策 %>  
 <div class="corona-detail">
      <div class="weight-bold-text">コロナ対策</div>
      <div class="form">
        <div class="weight-bold-text">
        混雑状況
        </div>
        <%= f.collection_select(:crowd_id, Crowd.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          コロナ対策 
        </div>
        <%= f.text_area :corona_measure, class:"hotel-area", id:"item-name", placeholder:" 宿でなされていたコロナ対策について（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>

   <%# /コロナ対策 %>  
   <%# 移動情報%>
   <div class="traffc-detail">
      <div class="weight-bold-text">施設のコロナ対策</div>
      <div class="form">
        <div class="weight-bold-text">
        移動手段と時間
        </div>
       <%= f.text_area :traffic, class:"hotel-area", id:"item-name", placeholder:"移動について自由記載 例）・新幹線:東京駅〜大阪駅(〇〇時間)・徒歩:大阪駅〜目的地〇〇に到着(〇〇分)。", maxlength:"40" %>
        <div class="weight-bold-text">

        </div>
       <div class="price-content">
          <div class="price-text">
            <span>交通費</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :fare, class:"price-input", id:"item-price", placeholder:"例）2000" %>
        </div>
      </div>
    </div>

    
    <%# /移動情報%>
    <%# /観光の詳細%>
     

      <%# 観光スポットの説明 %>
      <div class="items-explain">
        <div class="weight-bold-text">
          キャプション記入
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :spot_text, class:"items-text", id:"item-info", placeholder:"宿の説明 自由（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /観光スポットの説明 %>


    
 <%# /観光の情報 %>   
    
   
    <%# 注意書き %>
    <%# <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div> %>
    <%# /注意書き %>
   
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', trips_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <%# <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul> %>
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Travelgram,Inc.
    </p>
  </footer>
</div>

app/views/trips/index.html.erb
<%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%=link_to '宿泊施設の投稿',  new_tweet_path, class:"tweet-btn" %>
      <%=link_to '観光スポットの投稿',  new_trip_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>

app/views/trips/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>

  </header>

<%# 観光の情報 %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">観光スポット</h2>
    <%= form_with  model: @trip,local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>



   

    
    <%# 旅行タイトル %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <%# /旅行タイトル %>

      
 <%# 観光の詳細%>
     
      <%# 観光スポットの画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'trip[images][]', id:"travel-image" %>
        <div id="image-list"></div>
      </div>
    </div>

    <% @trip.images.each do |image| %>
  <%= image_tag image, class: 'images' %>
<% end %>
    <%# /観光スポットの画像 %>

<%# 観光スポットの動画 %>

    <%# <div class="field">
    <%= f.label :video %>
     <%# <%= f.file_field :video, :accept => 'video/*' %> 
 <%# </div>  %>
<%# /観光スポットの動画 %>
   
    <%# 観光曜日%>  
         <div class="weight-bold-text">
          観光した曜日
         
        </div>
        <%= f.collection_select(:week_id, Week.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    <%# /観光曜日%>  
      
       <%# 観光スポットの場所%>  
 <div class="hotel-detail">
      <div class="weight-bold-text">旅行の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :local, class:"hotel-area", id:"item-name", placeholder:"地域（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>
   <%# /観光スポットの場所%>  
     
     <%# 観光スポットの料金%>  
     <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>料金</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>料金(割引後)</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）5000" %>
        </div>
      </div>
    </div>
    <div class="weight-bold-text">
          元値
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_area :discount, class:"hotel-area", id:"item-name", placeholder:"例）5000", maxlength:"40" %>
        <span class="sell-yen"></span>
     <%# 観光スポットの料金%>  


      <%# コロナ対策 %>  
 <div class="corona-detail">
      <div class="weight-bold-text">コロナ対策</div>
      <div class="form">
        <div class="weight-bold-text">
        混雑状況
        </div>
        <%= f.collection_select(:crowd_id, Crowd.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          コロナ対策 
        </div>
        <%= f.text_area :corona_measure, class:"hotel-area", id:"item-name", placeholder:" 宿でなされていたコロナ対策について（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>

   <%# /コロナ対策 %>  
   <%# 移動情報%>
   <div class="traffc-detail">
      <div class="weight-bold-text">施設のコロナ対策</div>
      <div class="form">
        <div class="weight-bold-text">
        移動手段と時間
        </div>
       <%= f.text_area :traffic, class:"hotel-area", id:"item-name", placeholder:"移動について自由記載 例）・新幹線:東京駅〜大阪駅(〇〇時間)・徒歩:大阪駅〜目的地〇〇に到着(〇〇分)。", maxlength:"40" %>
        <div class="weight-bold-text">

        </div>
       <div class="price-content">
          <div class="price-text">
            <span>交通費</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :fare, class:"price-input", id:"item-price", placeholder:"例）2000" %>
        </div>
      </div>
    </div>

    
    <%# /移動情報%>
    <%# /観光の詳細%>
     

      <%# 観光スポットの説明 %>
      <div class="items-explain">
        <div class="weight-bold-text">
          キャプション記入
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :spot_text, class:"items-text", id:"item-info", placeholder:"宿の説明 自由（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /観光スポットの説明 %>


    
 <%# /観光の情報 %>   
    
   
    <%# 注意書き %>
    <%# <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div> %>
    <%# /注意書き %>
   
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <%# <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul> %>
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Travelgram,Inc.
    </p>
  </footer>
</div>

app/views/trips/show.html.erb
<%= render "shared/header" %>

<%#観光スポット%>
  <div class="detail-value"><%=link_to @trip.user.nickname, trip_user_path(@trip.user.id)%> </div>
        <%# <div class='item-img-content'>
      <%= image_tag @user.image ,class:"item-box-img" </div>  
   %>
    <h2 class="name">
      <%= @trip.title %>
    </h2>
     <div class='travel-img-content'>
     <% @trip.images.each do |image| %>
      <%= image_tag image ,class:"item-box-img"%>
    <%end%>
      <span><%= @trip.spot_text %></span>
   
   
   
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">都道府県</th>
          <td class="detail-value"><%= @trip.area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">地域</th>
          <td class="detail-value"><%= @trip.local %></td>
        </tr>
        <tr>
          <th class="detail-item">宿泊開始の曜日</th>
          <td class="detail-value"><%= @trip.week.name %></td>
        </tr>
        <tr>
          <th class="detail-item">宿の料金</th>
          <td class="detail-value"> ¥ <%= @trip.price%></td>
        </tr>
        <tr>
          <th class="detail-item">元値</th>
          <td class="detail-value"> ¥ <%= @trip.discount%></td>
        </tr>
        <tr>
          <th class="detail-item">混雑状況</th>
          <td class="detail-value"><%= @trip.crowd.name%></td>
        </tr>
        <tr>
          <th class="detail-item">宿のコロナ対策</th>
          <td class="detail-value"><%= @trip.corona_measure%></td>
        </tr>
        <tr>
          <th class="detail-item">移動手段と時間</th>
          <td class="detail-value"><%= @trip.traffic%></td>
        </tr>
        <tr>
          <th class="detail-item">交通費</th>
          <td class="detail-value"><%= @trip.fare%></td>
        </tr>
        <tr>
          <% if @trip.bookmark_by?(current_user) %>
      <td><%= link_to "お気に入りを外す", trip_bookmark_trips_path(@trip), method: :delete %></td>
    <% else %>
      <td><%= link_to "お気に入り", trip_bookmark_trips_path(@trip), method: :post %></td>
    <% end %>
        </tr>
      </tbody>
    </table>
    
    
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>easure
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な投稿の通報</span>
      </div>
    </div>

  <%#/観光スポット%>

  <%  if  current_user.id == @trip.user_id %>
    <%= link_to '投稿の編集', edit_trip_path(@trip.id), method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', trip_path(@trip.id), method: :delete, class:'item-destroy' %>
<% end %>






  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
 
 <%#追加コメント%>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@trip, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <a href="#" class='another-item'><%= "商品のカテゴリー名" %>をもっと見る</a>
</div>

<%= render "shared/footer" %>