config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  # get 'tweets/search'
  resources :tweets
  resources :trips
  resources :users
  resources :relationships
  resources :bookmarks
  # get 'spot', to: 'tweets#new_spot'
  #   post 'spot', to: 'tweets#create_spot'
  
    resource :users do
    resource :relationships, only: [:create, :destroy, :show,]
  end


 

  resources :tweets do
    resource :bookmarks
  end

  resources :trips do
    resource :bookmark_trips
  end
  
  resources :tweets do
    resources :comments, only: :create
  end

  resources :trips do
    resources :trip_comments, only: :create
  end
  
  resources :tweets do
    resources :users
  end

  resources :trips do
    resources :users
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many_attached :images
  has_many :bookmarks, dependent: :destroy
  has_many :comments  # commentsテーブルとのアソシエーション

  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  
  
  belongs_to_active_hash :area
  belongs_to_active_hash :crowd
  belongs_to_active_hash :day
  belongs_to_active_hash :week

  validates :area_id, numericality: { other_than: 1 }
  validates :images, :local, :title, :price,:hotel_text,presence: true
  # validates :video, :presence => true

  #動画投稿機能
  # mount_uploader :video, VideoUploader

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    # @tweets = Tweet.all.order("created_at DESC")
    # @trips = Trip.all.order("created_at DESC")

    @search = Tweet.ransack(params[:q])
    @tweet = @search.result(distinct: true).order("created_at DESC")


    @searchs = Trip.ransack(params[:q])
    @trip = @searchs.result(distinct: true).order("created_at DESC")
    

    @tweets = Tweet.all.includes(:user)
    # @trips = Trip.all.includes(:user)
    #  @user = User.find(params[:id])
  
  end

  def new
    @tweet = Tweet.new

  end
  
  def create
    #  binding.pry
    
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to  root_path
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweets = Tweet.all.includes(:user)
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
    # @trip = Trip.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])

  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet)
    else
      render :edit
    end
   
    respond_to do |format|
      if @article.update(article_params) && @article.video.recreate_versions!
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.destroy
      redirect_to root_path
    end
  end

  def bookmarks
    @tweets = current_user.bookmark_boards.includes(:user).recent
end

  #   unless @tweet.valid?
  #     flash.now[:alert] = @tweet.errors.full_messages
  #     render :new and return
  #   end
  #   session["devise.regist_data"] = {tweet: @tweet.attributes}
  #   @trip = @tweet.build_trip
  #   redirect_to  new_trip_path
  # end

  # def create_trip
  #   @tweet = Tweet.new(session["devise.regist_data"]["tweet"])
  #   @trip = Trip.new(trip_params)
  #   unless @trip.valid?
  #     flash.now[:alert] = @trip.errors.full_messages
  #     render :new_trip and return
  #   end
  #   @tweet.build_spot(@trip.attributes)
  #   @tweet.save
  #   session["devise.regist_data"]["tweet"].clear
  #   ###
  # end

# 省略

  # protected

  # def trip_params
  #   params.require(:trip).permit(:image,:price,:discount,:area_id,:day_id,:crowd_id,:title,:spot_text,:corona_measure,:traffic,:fare,:local,).merge(user_id: current_user.id)
  # end
  private
 
  def tweet_params
    params.require(:tweet).permit(:video,:price,:discount,:day_id,:area_id,:week_id,:crowd_id,:title,:hotel_text,:corona_measure,:local, images: []).merge(user_id: current_user.id)
  end

 
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>

  </header>

<%# 宿の情報 %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">宿泊施設</h2>
    <%= form_with model: @tweet,local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    
    <%# 旅行タイトル %>
    <div class="new-items">
      <div class="weight-bold-text">
        宿泊施設名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <%# /旅行タイトル %>

      
  <%# 宿の詳細%>
     
      <%# 宿の画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'tweet[images][]', id:"travel-image" %>
        <div id="image-list"></div>
      </div>
    </div>

    <% @tweet.images.each do |image| %>
  <%= image_tag image, class: 'images' %>
<% end %>
    <%# /宿の画像 %>

<%# 宿の動画 %>

    <div class="field">
    <%= f.label :video %>
    <%= f.file_field :video, :accept => 'video/*' %>
</div>
<%# /宿の動画 %>
         
   <%# 宿泊日数%>  
         <div class="weight-bold-text">
          滞在日数
         
        </div>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    <%# /宿泊日数%>  
      
       <%# 宿泊曜日%>  
         <div class="weight-bold-text">
          宿泊開始の曜日
         
        </div>
        <%= f.collection_select(:week_id, Week.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    <%# /宿泊曜日%>  

       <%# 宿の場所%>  
 <div class="hotel-detail">
      <div class="weight-bold-text">宿の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :local, class:"hotel-area", id:"item-name", placeholder:"地域（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>
   <%# /宿の場所%>  
     
     <%# 宿の料金%>  
     <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>宿の料金</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>料金(割引後)</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）5000" %>
        </div>
      </div>
    </div>
    <div class="weight-bold-text">
          元値
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_area :discount, class:"hotel-area", id:"item-name", placeholder:"例）5000", maxlength:"40" %>
        <span class="sell-yen"></span>
     <%# 宿の料金%>  


      <%# コロナ対策 %>  
 <div class="corona-detail">
      <div class="weight-bold-text">コロナ対策</div>
      <div class="form">
        <div class="weight-bold-text">
        混雑状況
        </div>
        <%= f.collection_select(:crowd_id, Crowd.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          宿のコロナ対策 
        </div>
        <%= f.text_area :corona_measure, class:"hotel-area", id:"item-name", placeholder:" 宿でなされていたコロナ対策について（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>
   <%# /コロナ対策 %>  
     

      <%# 宿の説明 %>
      <div class="items-explain">
        <div class="weight-bold-text">
          キャプション記入
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :hotel_text, class:"items-text", id:"item-info", placeholder:"宿の説明 自由（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /宿の説明 %>
  <%# /宿の情報 %>
    







    <%# 注意書き %>
    <%# <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div> %>
    <%# /注意書き %>
   
   

    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する"  ,class:"sell-btn" %>
      <%=link_to 'もどる', "trips_path", class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <%# <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul> %>
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Travelgram,Inc.
    </p>
  </footer>
</div>

app/views/tweets/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      今だからこそ旅行へ！！！
    </h2>
    <p class='service-explain'>
      実際に行った人の生の声が聞ける
    </p>
    <p class='service-explain'>
    旅行専用投稿アプリ
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("jaran.png", class:"jalan-btn"), "https://www.jalan.net/" %>
      <%= link_to image_tag("yahoo.png", class:"yahoo-btn"), "https://travel.yahoo.co.jp/" %>
       <%= link_to image_tag("rurubu.png", class:"his-btn"), "https://www.rurubu.travel/?utm_medium=cpc&utm_source=google&utm_campaign=google_rurubu-htl_02-brandplus&utm_content=rurubutop__txt_rsa-1_&cid=1835687&gclid=CjwKCAjw-5v7BRAmEiwAJ3DpuLemL4PcnvfCuYZAL5oo2x4LsV0sh1xQAudTeK4fzejRd6v3Q4qc8hoCrHAQAvD_BwE" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# 日本地図 %>
  <%# <div class='select-reason-contents'>
     <%= link_to image_tag('japanese_map.png' ), "/" %>
  <%# </div>   %> 






<%= render "shared/japanmap" %> 















  <%# /日本地図 %>

<%# 検索%>


<%# 宿泊施設・観光スポット検索欄%>
<span class= 'search-btn'>検索</span>
<%= search_form_for @search do |f| %>
  <%= f.label :title_cont, '宿泊施設・観光スポット名' %>
  <%= f.search_field :title_cont %>




<%=f.label :area_id_eq,'都道府県'%>
<%= f.collection_select :area_id_eq, Area.all,:id,:name, include_blank: '指定なし' %>
  
  



 <%= f.label :local_cont, '地域' %>
  <%= f.search_field :local_cont %>

  
  
  
  <%= f.label :price %>
  <%= f.radio_button :price_lteq, '' %>指定なし
  <%= f.radio_button :price_lteq, '5000' %>5000円以下
  <%= f.radio_button :price_lteq, '7500' %>7500円以下
  <%= f.radio_button :price_lteq, '10000' %>10000円以下

<%= f.submit '検索' %>

<% end %>
  

<%# /宿泊施設・観光スポット検索欄%>




 
<%# 投稿一覧 %>
  <%# 宿泊施設投稿一覧 %>
  <div class='item-contents'>
    <h2 class='title'>旅行の投稿一覧</h2>
     
    
   <ul class='item-lists'>
      
      <% @tweet.each do |tweet| %>
    
    <li class='list'>
      <div class='item-info'>
          <h3 class='item-name'>
            <%= tweet.title %>
          </h3>
           <div class='item-name'>
            <%= tweet.area.name%>    <%= tweet.local%>         
          </div>
          
             <div class='item-name'>
            <%= "宿泊施設"%>
           </div> 
        <div class='item-img-content'>
        <% tweet.images.each do |image| %>
         <%= link_to  tweet_path(tweet.id) do %>
          <%= image_tag image ,class: 'images'   %>
        <% end %>
        <% end %>
         </div>

         <p>
          <strong>Video:</strong>
        </p>
         <%# <p>
       <%= link_to tweet.video_url.to_s do %>
      <%# <%= image_tag(tweet.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
   <%# <% end %> 
<%# </p>   %>

       
        <div class='item-info'>
          
          <div class='item-price'>
            <span><%= tweet.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
      </li>
       <% end %>
        
        <%# /宿泊施設投稿一覧 %>
  

  <%# 観光スポット投稿一覧 %>
    <ul class='item-lists'>
      
      <% @trip.each do |trip| %>
    
    <li class='list'>
      <div class='item-info'>
          <h3 class='item-name'>
            <%= trip.title %>
          </h3>
           <div class='item-name'>
            <%= trip.area.name%>    <%= trip.local%>         
          </div>
          
             <div class='item-name'>
            <%= "観光スポット"%>
           </div> 
        <div class='item-img-content'>
        <% trip.images.each do |image| %>
        <%= link_to  trip_path(trip.id) do %>

          <%= image_tag image ,class: 'images'   %>
        <% end %>
        <% end %>
         </div>

        <p>
          <strong>Video:</strong>
        </p>
         <%# <p>
       <%= link_to trip.video_url.to_s do %>
      <%# <%= image_tag(trip.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %> 
       <%# <% end %> 
        <%# </p>  %>

       
        <div class='item-info'>
          
          <div class='item-price'>
            <span><%= trip.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
      </li>
       <% end %>

      <%# お気に入り %>
      
       <%# <div class="row d-flex">
  <%= render @tweets %>
<%# </div>  %>
     <%# /お気に入り %>

    
       <%# /観光スポット投稿一覧 %>
        

      
      

     
  <%# /投稿一覧 %>

 




<div class='purchase-btn'>
  <span class='purchase-btn-text'>投稿する</span>
  <a href="/trips">
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>
<%# <%= render "shared/footer" %> 

app/views/tweets/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>

  </header>

<%# 宿の情報 %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">宿泊施設</h2>
    <%= form_with  model: @tweet,local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    
    <%# 旅行タイトル %>
    <div class="new-items">
      <div class="weight-bold-text">
        宿泊施設名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <%# /旅行タイトル %>

      
  <%# 宿の詳細%>
     
      <%# 宿の画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'tweet[images][]', id:"travel-image" %>
        <div id="image-list"></div>
      </div>
    </div>

    <% @tweet.images.each do |image| %>
  <%= image_tag image, class: 'images' %>
<% end %>
    <%# /宿の画像 %>

<%# 宿の動画 %>

    <%# <div class="field">
    <%= f.label :video %>
     <%# <%= f.file_field :video, :accept => 'video/*' %> 
   <%# </div>    %>

         
   <%# 宿泊日数%>  
         <div class="weight-bold-text">
          滞在日数
         
        </div>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    <%# /宿泊日数%>  
      
       <%# 宿泊曜日%>  
         <div class="weight-bold-text">
          宿泊開始の曜日
         
        </div>
        <%= f.collection_select(:week_id, Week.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    <%# /宿泊曜日%>  

       <%# 宿の場所%>  
 <div class="hotel-detail">
      <div class="weight-bold-text">宿の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :local, class:"hotel-area", id:"item-name", placeholder:"地域（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>
   <%# /宿の場所%>  
     
     <%# 宿の料金%>  
     <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>宿の料金</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>料金(割引後)</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）5000" %>
        </div>
      </div>
    </div>
    <div class="weight-bold-text">
          元値
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_area :discount, class:"hotel-area", id:"item-name", placeholder:"例）5000", maxlength:"40" %>
        <span class="sell-yen"></span>
     <%# 宿の料金%>  


      <%# コロナ対策 %>  
 <div class="corona-detail">
      <div class="weight-bold-text">コロナ対策</div>
      <div class="form">
        <div class="weight-bold-text">
        混雑状況
        </div>
        <%= f.collection_select(:crowd_id, Crowd.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          宿のコロナ対策 
        </div>
        <%= f.text_area :corona_measure, class:"hotel-area", id:"item-name", placeholder:" 宿でなされていたコロナ対策について（必須 40文字まで)", maxlength:"40" %>
      </div>
    </div>
   <%# /コロナ対策 %>  
     

      <%# 宿の説明 %>
      <div class="items-explain">
        <div class="weight-bold-text">
          キャプション記入
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :hotel_text, class:"items-text", id:"item-info", placeholder:"宿の説明 自由（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /宿の説明 %>
  <%# /宿の情報 %>
    







    <%# 注意書き %>
    <%# <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div> %>
    <%# /注意書き %>
   
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <%# <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul> %>
    <%= link_to image_tag('plane2-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Travelgram,Inc.
    </p>
  </footer>
</div>

app/views/tweets/show.html.erb
<%= render "shared/header" %>



    


    <%# 商品が売れていない場合はこちらを表示しましょう %>
    <%# <%= link_to '購入画面に進む', "#" ,class:"item-red-btn"%> 
    <%# //商品が売れていない場合はこちらを表示しましょう %>


  <%#宿泊施設%>
<div class="detail-value"><%=link_to @tweet.user.nickname, tweet_user_path(@tweet.user.id)%> </div>
        <%# <div class='item-img-content'>
      <%= image_tag @user.image ,class:"item-box-img" %> 
  
  
    <h2 class="name">
      <%= @tweet.title %>
    </h2>
      <div class='travel-img-content'>
      <% @tweet.images.each do |image| %>
      <%= image_tag image ,class:"item-box-img" %>
      <%end%>
      <span><%= @tweet.hotel_text %></span>
   
   
   
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">都道府県</th>
          <td class="detail-value"><%= @tweet.area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">地域</th>
          <td class="detail-value"><%= @tweet.local %></td>
        </tr>
        <tr>
          <th class="detail-item">宿泊日数</th>
          <td class="detail-value"><%= @tweet.day.name %></td>
        </tr>
        <tr>
          <th class="detail-item">宿泊開始の曜日</th>
          <td class="detail-value"><%= @tweet.week.name %></td>
        </tr>
        <tr>
          <th class="detail-item">宿の料金</th>
          <td class="detail-value"> ¥ <%= @tweet.price%></td>
        </tr>
        <tr>
          <th class="detail-item">元値</th>
          <td class="detail-value"> ¥ <%= @tweet.discount%></td>
        </tr>
        <tr>
          <th class="detail-item">混雑状況</th>
          <td class="detail-value"><%= @tweet.crowd.name%></td>
        </tr>
        <tr>
          <th class="detail-item">宿のコロナ対策</th>
          <td class="detail-value"><%= @tweet.corona_measure%></td>
        </tr>
        <tr>
          <% if @tweet.bookmark_by?(current_user) %>
      <td><%= link_to "お気に入りを外す", tweet_bookmarks_path(@tweet), method: :delete %></td>
    <% else %>
      <td><%= link_to "お気に入り",tweet_bookmarks_path(@tweet), method: :post %></td>
    <% end %>
        </tr>
      </tbody>
    </table>
   
   <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り </span>
      </div>easure
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
<%#お気に入り%>

   

  <%#宿泊施設%>

  

<%  if  current_user.id == @tweet.user_id %>
    <%= link_to '投稿の編集', edit_tweet_path(@tweet.id), method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', tweet_path(@tweet.id), method: :delete, class:'item-destroy' %>
<% end %>






  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>

<%#追加コメント%>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
 
    
  
  <a href="#" class='another-item'><%= "商品のカテゴリー名" %>をもっと見る</a>
</div>

<%= render "shared/footer" %>