config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  # get 'tweets/search'
  resources :tweets
  resources :trips
  resources :users
  resources :relationships
  resources :bookmarks
  # get 'spot', to: 'tweets#new_spot'
  #   post 'spot', to: 'tweets#create_spot'
  
    resource :users do
    resource :relationships, only: [:create, :destroy, :show,]
  end


 

  resources :tweets do
    resource :bookmarks
  end

  resources :trips do
    resource :bookmark_trips
  end
  
  resources :tweets do
    resources :comments, only: :create
  end

  resources :trips do
    resources :trip_comments, only: :create
  end
  
  resources :tweets do
    resources :users
  end

  resources :trips do
    resources :users
  end

end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_follow.html.erb
 
   <ul class='lists-right'>
       <li><%= link_to (@tweet||@trip).user.image, user_path(current_user.id), class: "user-image"  %></li>
       <li><%= link_to (@tweet||@trip).user.nickname, user_path(current_user.id), class: "user-nickname"  %></li>
       <li><%= link_to "フォロワー",  users_relationships_path, class: "user-nickname"  %></li>
       <li><%= link_to "フォロー中",   users_relationships_path, class: "user-nickname"  %></li>
 
 <%  if current_user.id == (@tweet.user.id || @trip.user.id)%>
    <%= link_to 'プロフィールの編集',  '#', method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to 'ログアウト', '#', method: :delete, class:'item-destroy' %>
    <%= link_to '削除', '#', method: :delete, class:'item-destroy' %>
  
  
    
    

    <%else %>

    
  <% if current_user.following?(@user) %>
    <%= link_to 'フォロー外す', tweet_user_path(@tweet.user.id) || trip_user_path(@trip.user.id), method: :delete %>
  <% else %>
    <%= link_to 'フォローする', tweet_user_path(@tweet.user.id) || trip_user_path(@trip.user.id), method: :POST %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    今だからお得に旅行に行こう！
  </p>
  <h2 class='ad-footer-title'>
    今すぐ旅行予約！
  </h2>
  <div class='store-btn'>
   <%= link_to image_tag("jaran.png", class:"jalan-btn"), "https://www.jalan.net/" %>
      <%= link_to image_tag("yahoo.png", class:"yahoo-btn"), "https://travel.yahoo.co.jp/" %>
      <%= link_to image_tag("rurubu.png", class:"his-btn"), "https://www.rurubu.travel/?utm_medium=cpc&utm_source=google&utm_campaign=google_rurubu-htl_02-brandplus&utm_content=rurubutop__txt_rsa-1_&cid=1835687&gclid=CjwKCAjw-5v7BRAmEiwAJ3DpuLemL4PcnvfCuYZAL5oo2x4LsV0sh1xQAudTeK4fzejRd6v3Q4qc8hoCrHAQAvD_BwE" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  
  <%# 旅行検索%>
  <div class='search-bar-contents'>
    <%= link_to image_tag("plane2-logo.png", class:"furima-icon"), "/" %>
    
    <%# 元からある検索欄%>
    <%# <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
       <%# </button>
    </form>
  </div>  %> 
  <%# /元からある検索欄%>

  


  
  
   <%# 追加した検索欄%>
   <%# <h1>
  旅行検索
</h1>
<%= search_form_for @p, url: products_search_path do |f| %>
  <%# <%= f.label :name_eq, '商品名' %> 
  <%# <%= f.collection_select :name_eq, @products, :name, :name,  include_blank: '指定なし' %>
  <%# <br>
  <%= f.submit '検索' %>
<%# <% end %> 

   <%# /追加した検索欄%>
  <%# /旅行検索%>
  
  <div class='nav'>
   
    <ul class='lists-right'>
      <%# <% if user_signed_in? && current_user.id == @user.id%> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
    <% if user_signed_in? %>
       <li><%= link_to current_user.image, user_path(current_user.id), class: "user-image"  %></li>
       <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname"  %></li>
       <li><%= link_to 'ログアウト',destroy_user_session_path , method: :delete, class: "logout"  %></li>
     <% else %>
      <li><%= link_to 'ログイン', new_user_session_path , class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_japanmap.html.erb
<html>
<head>
<title>japanese_map</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>  
  <%# <%= link_to image_tag('japanese_map.gif' ), "/"  , %> %>
  
<img src="japanese_map.gif" width="1920" height="1080" border="0" alt="" class="japanese_map_Map">
<div class ="japanese_map_Map">
<a shape="poly" alt="" coords="767,693, 746,693, 743,693, 742,689, 742,647, 743,644, 746,644, 787,644, 790,645, 791,648, 791,669, 792,682, 791,690, 788,693, 781,693, 767,693" href="#miyazaki"></a>
<a shape="poly" alt="" coords="1030,525, 1031,516, 1031,525, 1030,525" href="#areaname"></a>
<a shape="poly" alt="" coords="1036,517, 1035,527, 1034,522, 1036,517" href="#isikawa"></a>
<a shape="poly" alt="" coords="1014,657, 1004,657, 1010,655, 1014,657" href="#mie"></a>
<a shape="poly" alt="" coords="1201,587, 1248,587, 1252,583, 1252,539, 1248,535, 1216,535, 1213,536, 1213,539, 1213,559, 1212,578, 1212,539, 1213,535, 1217,534, 1248,534, 1252,535, 1253,538, 1253,584, 1252,587, 1250,588, 1225,588, 1201,587" href="#areaname"></a>
<a shape="poly" alt="" coords="875,540, 903,540, 906,541, 907,544, 907,555, 906,560, 901,561, 892,561, 876,561, 874,558, 875,555, 875,540" href="#tottori"></a>
<a shape="poly" alt="" coords="853,561, 842,561, 837,559, 837,553, 837,542, 838,540, 840,540, 847,540, 858,540, 867,540, 870,543, 870,554, 869,559, 865,561, 853,561" href="#simane"></a>
<a shape="poly" alt="" coords="1013,539, 1018,540, 1021,541, 1022,553, 1019,554, 981,554, 978,551, 978,547, 978,542, 981,540, 982,539, 982,537, 987,539, 986,542, 986,545, 989,545, 994,546, 995,543, 995,537, 998,535, 1001,537, 1003,541, 1003,545, 1007,543, 1009,544, 1009,542, 1009,538, 1013,539"
href="#hukui"></a>
<a shape="poly" alt="" coords="933,612, 940,612, 947,612, 951,616, 951,654, 947,658, 940,658, 934,658, 933,655, 932,634, 933,612" href="#oosaka"></a>
<a shape="poly" alt="" coords="889,652, 911,652, 914,655, 914,665, 910,669, 900,670, 867,670, 864,669, 863,666, 864,656, 867,652, 877,652, 889,652" href="#tokusima"></a>
<a shape="poly" alt="" coords="863,646, 863,641, 863,633, 865,629, 909,630, 914,634, 914,640, 914,647, 891,648, 868,647, 865,648, 863,646" href="#kagawa"></a>
<a shape="poly" alt="" coords="746,541, 746,561, 746,572, 745,578, 738,579, 722,579, 719,578, 718,575, 718,541, 746,541" href="#saga"></a>
<a shape="poly" alt="" coords="1182,645, 1179,647, 1178,649, 1180,650, 1181,658, 1179,665, 1173,664, 1167,664, 1161,667, 1157,671, 1149,676, 1140,676, 1139,674, 1139,672, 1139,644, 1178,644, 1180,643, 1182,645" href="#kanagawa"></a>
<a shape="poly" alt="" coords="1078,479, 1078,526, 1075,530, 1055,530, 1051,529, 1051,525, 1051,511, 1058,499, 1067,489, 1078,479" href="#toyama"></a>
<a shape="poly" alt="" coords="1063,676, 1031,676, 1028,675, 1027,672, 1027,640, 1029,636, 1034,636, 1039,636, 1045,637, 1046,643, 1052,643, 1060,643, 1063,646, 1063,676" href="#aichi"></a>
<a shape="poly" alt="" coords="1113,610, 1121,610, 1130,610, 1134,613, 1134,636, 1131,639, 1096,639, 1092,636, 1092,622, 1092,615, 1093,611, 1099,610, 1113,610" href="#yamanasi"></a>
<a shape="poly" alt="" coords="955,572, 955,544, 958,540, 964,540, 970,540, 974,542, 974,549, 973,556, 976,560, 977,563, 977,601, 976,604, 973,605, 961,605, 956,604, 955,599, 956,589, 955,572" href="#kyoto"></a>
<a shape="poly" alt="" coords="837,607, 837,566, 870,566, 870,607, 837,607" href="#hirosima"></a>
<a shape="poly" alt="" coords="876,565, 893,565, 903,565, 907,568, 907,574, 907,585, 907,603, 906,607, 903,608, 876,608, 875,605, 875,568, 876,565" href="#okayama"></a>
<a shape="poly" alt="" coords="787,541, 792,550, 792,565, 792,577, 791,579, 755,579, 751,578, 750,574, 750,541, 768,540, 787,541" href="#hukuoka"></a>
<a shape="poly" alt="" coords="1208,535, 1208,554, 1208,566, 1207,572, 1202,574, 1191,574, 1172,574, 1169,573, 1168,570, 1168,535, 1171,535, 1189,534, 1208,535" href="#totigi"></a>
<a shape="poly" alt="" coords="1163,639, 1149,639, 1141,639, 1139,635, 1139,628, 1139,614, 1140,611, 1143,610, 1193,610, 1196,612, 1196,616, 1196,620, 1194,630, 1188,638, 1176,639, 1163,639" href="#tokyo"></a>
<a shape="poly" alt="" coords="1164,535, 1164,555, 1164,566, 1163,572, 1157,574, 1145,574, 1126,574, 1123,573, 1122,570, 1122,535, 1125,535, 1144,534, 1164,535" href="#gunnma"></a>
<a shape="poly" alt="" coords="652,795, 648,793, 647,789, 647,747, 651,742, 669,741, 677,745, 679,753, 678,766, 678,787, 675,794, 668,796, 660,795, 652,795" href="#okinawa"></a>
<a shape="poly" alt="" coords="812,607, 808,602, 808,547, 812,541, 820,540, 828,540, 831,541, 832,544, 832,607, 812,607" href="#yamaguchi"></a>
<a shape="poly" alt="" coords="998,678, 998,640, 999,637, 1002,636, 1010,636, 1018,636, 1022,640, 1022,657, 1022,675, 1017,691, 1013,699, 1010,708, 1005,717, 999,719, 998,718, 998,715, 998,678" href="#mie"></a>
<a shape="poly" alt="" coords="981,595, 982,576, 981,565, 982,560, 988,559, 1001,559, 1005,562, 1005,628, 1001,632, 992,632, 985,632, 982,631, 981,628, 981,595" href="#siga"></a>
<a shape="poly" alt="" coords="703,579, 703,638, 696,639, 690,637, 687,631, 687,547, 688,543, 691,541, 699,540, 709,540, 714,543, 714,575, 712,578, 707,578, 703,579" href="#nagasaki"></a>
<a shape="poly" alt="" coords="1123,578, 1191,578, 1195,579, 1196,583, 1196,600, 1195,604, 1191,605, 1123,605, 1123,578" href="#saitama"></a>
<a shape="poly" alt="" coords="1134,644, 1134,672, 1133,675, 1130,676, 1072,676, 1069,675, 1068,672, 1068,644, 1101,643, 1134,644" href="#sizuoka"></a>
<a shape="poly" alt="" coords="859,630, 859,650, 859,662, 858,668, 854,670, 846,670, 833,669, 812,670, 809,669, 808,666, 808,637, 809,632, 813,630, 836,629, 859,630" href="#ehime"></a>
<a shape="poly" alt="" coords="955,643, 955,614, 956,611, 959,610, 972,610, 977,612, 977,619, 977,632, 979,636, 984,636, 990,636, 994,639, 994,650, 994,665, 993,673, 991,676, 985,676, 975,676, 959,676, 956,675, 955,672, 955,643" href="#nara"></a>
<a shape="poly" alt="" coords="1201,587, 1201,580, 1204,578, 1212,578, 1212,538, 1216,534, 1249,534, 1252,535, 1252,538, 1252,584, 1252,586, 1250,587, 1201,587" href="#ibaragi"></a>
<a shape="poly" alt="" coords="791,737, 783,742, 749,742, 743,738, 742,729, 743,718, 742,710, 732,709, 720,710, 711,708, 708,699, 710,698, 713,698, 791,698, 792,717, 791,737" href="#kagosima"></a>
<a shape="poly" alt="" coords="861,674, 909,674, 913,675, 914,679, 914,687, 913,694, 906,697, 816,697, 810,695, 808,689, 808,678, 811,674, 822,674, 861,674" href="#kouchi"></a>
<a shape="poly" alt="" coords="1136,422, 1164,422, 1168,423, 1169,427, 1169,478, 1168,482, 1165,483, 1154,483, 1150,479, 1150,469, 1151,460, 1149,453, 1142,451, 1133,452, 1107,452, 1104,451, 1103,448, 1103,432, 1104,424, 1108,422, 1118,422, 1136,422" href="#yamagata"></a>
<a shape="poly" alt="" coords="934,662, 941,662, 948,663, 951,668, 950,673, 951,679, 955,681, 989,681, 993,682, 994,685, 994,715, 993,719, 990,720, 938,720, 934,718, 933,714, 933,664, 934,662" href="#wakayama"></a>
<a shape="poly" alt="" coords="912,573, 912,556, 912,546, 914,541, 919,540, 929,540, 947,540, 950,541, 951,544, 951,603, 950,607, 946,608, 929,608, 919,608, 913,606, 912,601, 912,591, 912,573" href="#hyougo"></a>
<a shape="poly" alt="" coords="791,639, 742,639, 742,587, 742,584, 745,583, 788,583, 791,584, 792,586, 792,613, 791,639" href="#ooita"></a>
<a shape="poly" alt="" coords="1046,586, 1046,627, 1045,631, 1042,632, 1013,632, 1010,631, 1009,628, 1009,562, 1010,560, 1013,559, 1023,559, 1027,557, 1027,553, 1027,543, 1030,540, 1038,539, 1045,541, 1046,547, 1046,555, 1046,586" href="#gihu"></a>
<a shape="poly" alt="" coords="737,584, 737,693, 708,693, 708,587, 708,585, 710,584, 737,584" href="#kumamoto"></a>
<a shape="poly" alt="" coords="1252,418, 1178,418, 1174,417, 1173,413, 1173,365, 1174,362, 1177,361, 1203,361, 1218,361, 1225,362, 1226,364, 1225,367, 1225,373, 1228,381, 1237,392, 1252,408, 1252,418" href="#iwate"></a>
<a shape="poly" alt="" coords="1136,361, 1165,361, 1168,362, 1169,365, 1169,414, 1168,417, 1165,418, 1107,418, 1104,417, 1103,414, 1103,365, 1104,362, 1107,361, 1136,361" href="#akita"></a>
<a shape="poly" alt="" coords="1252,671, 1244,675, 1206,675, 1202,674, 1201,670, 1201,597, 1202,593, 1205,592, 1252,592, 1253,631, 1252,671" href="#chiba"></a>
<a shape="poly" alt="" coords="1252,530, 1150,530, 1150,491, 1149,489, 1150,487, 1173,487, 1251,487, 1252,490, 1253,510, 1252,530" href="#hukusima"></a>
<a shape="rect" alt="" coords="1083,456,1145,530" href="#niigata"></a>
<a shape="poly" alt="" coords="1252,483, 1178,483, 1174,482, 1173,478, 1173,427, 1174,423, 1178,422, 1251,422, 1252,425, 1253,454, 1252,483" href="#miyagi"></a>
<a shape="poly" alt="" coords="1103,356, 1103,320, 1105,313, 1112,311, 1148,311, 1155,313, 1157,320, 1157,328, 1157,335, 1161,339, 1171,338, 1179,338, 1182,338, 1183,334, 1183,316, 1183,305, 1184,298, 1188,295, 1199,295, 1217,295, 1224,297, 1226,304, 1226,356, 1164,357, 1103,356" href="#aomori"></a>
<a shape="poly" alt="" coords="1051,587, 1051,539, 1052,535, 1055,534, 1113,534, 1117,535, 1118,539, 1118,601, 1117,604, 1114,605, 1097,605, 1089,606, 1087,610, 1088,619, 1088,635, 1087,638, 1084,639, 1055,639, 1052,638, 1051,635, 1051,587" href="#nagano"></a>
<a shape="poly" alt="" coords="1109,286, 1104,279, 1104,227, 1108,221, 1117,219, 1128,220, 1137,219, 1138,157, 1138,94, 1141,91, 1145,91, 1243,91, 1341,91, 1348,93, 1350,100, 1350,244, 1347,252, 1338,254, 1255,253, 1171,254, 1171,265, 1171,278, 1166,286, 1109,286" href="#hokkaido"></a>
</div>
</body>
</html>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "plane2-logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("plane2-logo.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_username.html.erb
<header class='top-page-header'>
  
  
  <div class='search-bar-contents'>
    <%= link_to image_tag("plane2-logo.png", class:"furima-icon"), "/" %>
    
   
  
  <div class='nav'>
   
    <ul class='lists-right'>
      <%# <% if user_signed_in? && current_user.id == @user.id%> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
    <% if  %>
       <li><%= link_to @tweet.user.image, user_path(current_user.id), class: "user-image"  %></li>
       <li><%= link_to @tweet.user.nickname, user_path(current_user.id), class: "user-nickname"  %></li>
       <li><%= link_to 'ログアウト',destroy_user_session_path , method: :delete, class: "logout"  %></li>
     <% else %>
      <li><%= link_to 'ログイン', new_user_session_path , class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
      <li><%= link_to '宿泊施設お気に入り一覧', tweet_bookmarks_path(tweet_url), class: "bookmark" %></li>
      <li><%= link_to '観光スポットお気に入り一覧',  trip_bookmark_trips_path(trip_url), class: "bookmark_trip" %></li>
    </ul>
  </div>
</header>